### ISSUE TITLE
US intl. with dead keys

### ISSUE THREAD

**Issue by carlosrve** [thomasfaingnaert/win-us-intl-altgr#2]
I found your repo looking for a way to install the linux "US intl. with dead keys" on Windows 10. I see that you use "US intl. with altgr dead keys". The main difference is that I am used to type altgr for the standard US character (quote, double quotes, etc). And use the dead key without the altgr. This is because I live in a Spanish speaking country so I use more often the accents and ñ than the quotes and such. But for writing code, I still can have my US characters on hand.

I would like to contribute to this repo with a "US intl. with dead keys" layout, so I have a couple of questions:

1. Are you willing to make this a more general US intl. repo so I can contribute here on the same repo.

2. Did you create your layout from the ground up, or did you manage somehow to export the layout from linux to use it as base?

Regards

**Comment by thomasfaingnaert** [comment]
I believe you can just use the standard United States International keyboard layout that ships by default on Windows.
As for how I created the layout: first, I opened the default US Intl keyboard layout in Microsoft Keyboard Layout Creator, and then I manually moved the dead key combinations to AltGr.
If the default US Intl doesn't work as expected, I'd love to expand this repo to provide more general keyboard layouts.
