### ISSUE TITLE
showing 2 keyboard layouts, actually switching between 3

### ISSUE THREAD

**Issue by xdp0** [thomasfaingnaert/win-us-intl-altgr#9]
I use Windows 11.

I have two keyboard layouts installed: first is the "United Stated (International) - Alt Gr dead keys" as the default and the Russian layout also. Only two are showed in the keyboard layout list from the language bar in system tray.

Layout switching is binded to Ctrl+Shift, but I use Caps Lock (there are different tools to bind Caps Lock to switch layouts, I use [lswitch](https://github.com/valodzka/lswitch/)).

When I use Ctrl + Shift, it switches between International and Russian layouts, everything is fine.

When I use Caps Lock or Win + Tab, it iterates over three layouts: default English (without Alt Gr), International and Russian.

How can I remove default English layout when it even does not show in list?

**Comment by thomasfaingnaert** [comment]
I'm not familiar with lswitch, so I'm not entirely sure what the issue could be. From a quick glance at the source, it seems it sends `WM_INPUTLANGCHANGEREQUEST`, which I presume is the same thing CTRL+SHIFT does. You might want to ask over at the lswitch repo for ideas on how to solve this issue, as I don't think it's a problem with the keyboard layout itself.

Maybe you could also try an alternative to lswitch? E.g. using AutoHotKey to bind CAPS to CTRL+SHIFT?
